const NAME_SPACE = 'Patients';

const constants = {
  FETCH_PATIENTS_CANCEL: `${NAME_SPACE}/FETCH_PATIENTS_CANCEL`,
  FETCH_PATIENTS_FAILURE: `${NAME_SPACE}/FETCH_PATIENTS_FAILURE`,
  FETCH_PATIENTS_REQUEST: `${NAME_SPACE}/FETCH_PATIENTS_REQUEST`,
  FETCH_PATIENTS_SUCCESS: `${NAME_SPACE}/FETCH_PATIENTS_SUCCESS`,
  FETCH_PATIENTS: `${NAME_SPACE}/FETCH_PATIENTS`,
  PING: 'PING'
};

export default constants;